<a href="https://colab.research.google.com/github/vrinda561/Predict-Bank-Churn/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [26]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [27]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [28]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [29]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [30]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])

In [32]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])] ,remainder = 'passthrough')
x =np.array(ct.fit_transform(x))

In [34]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.20,random_state=0)

### Feature Scaling

In [36]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [37]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [38]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

### Adding the second hidden layer

In [39]:
ann.add(tf.keras.layers.Dense(units =6, activation='relu'))

### Adding the output layer

In [40]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [41]:
ann.compile(optimizer ='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [42]:
ann.fit(x_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5509 - accuracy: 0.7722
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4601 - accuracy: 0.8027
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4376 - accuracy: 0.8151
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4266 - accuracy: 0.8220
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4194 - accuracy: 0.8254
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4123 - accuracy: 0.8290
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4027 - accuracy: 0.8332
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3922 - accuracy: 0.8371
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3810 - accuracy: 0.8445
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3709 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation



Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [43]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


### Predicting the Test set results

In [44]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1506   89]
 [ 195  210]]


0.858